### ISSUE TITLE
No Minimum Font Size

### ISSUE THREAD

**Issue by Samuel-Harwood** [ThatGuyDed/team-software-engineering#4]
Basically the same issue as last time, but now with the font scaling going below the minimum amount to where text is visible
![image](https://user-images.githubusercontent.com/101341494/235901024-ada81e92-c042-452c-9cef-1210a725ed9d.png)

**Comment by ThatGuyDed** [comment]
Solved by forcing the font size to be locked between 200-300 in the slider
